require "jed.settings"
require "jed.mappings"
require "jed.plugins"
require "jed.colorscheme"
require "jed.lualine"
require "jed.telescope"
require "jed.nvim-tree"
require "jed.whichkey"
require "jed.gitsigns"
require "jed.alpha"
require "jed.comments"
require "jed.projects"
require "jed.bufferline"
require "jed.cmp"

